# Generated by Django 6.0.2 on 2026-03-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_userfcmtoken"),
        ("payments", "0006_payment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="orders.order",
            ),
        ),
    ]
