# Generated by Django 6.0.2 on 2026-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_partnerbankdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerwallet",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
