# Generated by Django 6.0.2 on 2026-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_partnerwallet_commission_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerbankdetail",
            name="passbook_image",
            field=models.ImageField(blank=True, null=True, upload_to="bank_proofs/"),
        ),
    ]
