# Generated by Django 5.2.11 on 2026-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
