# Generated by Django 5.2.11 on 2026-03-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="order_id",
        ),
    ]
