# Generated by Django 5.2.11 on 2026-03-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_notification_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="order",
        ),
    ]
