# Generated by Django 6.0.2 on 2026-02-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
