# Generated by Django 6.0.2 on 2026-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_type_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="category/"),
        ),
    ]
