# Generated by Django 6.0.2 on 2026-02-17 12:59

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_type_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.type"
            ),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="services.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="subcategory",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="type",
                chained_model_field="type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.subcategory",
            ),
        ),
    ]
