# Generated by Django 6.0.2 on 2026-02-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="type",
            name="image",
        ),
        migrations.AddField(
            model_name="type",
            name="icon",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
