# Generated by Django 6.0.2 on 2026-02-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_remove_type_image_type_icon_delete_cartitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Type",
            new_name="Category",
        ),
    ]
