# Generated by Django 6.0.2 on 2026-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_rename_type_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
