# Generated by Django 5.2.11 on 2026-03-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_category_icon_address'),
        ('services', '0010_banner'),
    ]

    operations = [
    ]
