# Generated by Django 5.2.11 on 2026-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_merge_0009_alter_category_icon_address_0010_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
