# Generated by Django 5.2.11 on 2026-03-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_order_is_paid_order_razorpay_order_id_and_more"),
        ("services", "0012_alter_category_icon_delete_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
