# Generated by Django 5.2.11 on 2026-03-07 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_order_is_paid_order_razorpay_order_id_and_more"),
        ("services", "0013_complaint_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="orders.order",
            ),
        ),
    ]
