# Generated by Django 5.2.11 on 2026-03-07 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_order_is_paid_order_razorpay_order_id_and_more"),
        ("services", "0014_alter_complaint_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="message",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="complaint",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
    ]
