# Generated by Django 5.2.11 on 2026-03-13 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_userfcmtoken"),
        ("services", "0015_complaint_message_alter_complaint_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="subject",
            field=models.CharField(default="Order Issue", max_length=200),
        ),
        migrations.AddField(
            model_name="complaint",
            name="user_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
            ),
        ),
    ]
