# Generated by Django 6.0.2 on 2026-03-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_complaint_subject_complaint_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="complaints/"),
        ),
    ]
