# Generated by Django 5.2.12 on 2026-03-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardlink',
            options={'managed': False, 'verbose_name_plural': 'Custom Dashboard'},
        ),
    ]
