# Generated by Django 6.0.2 on 2026-02-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("partner", "Partner"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
