# Generated by Django 5.2.11 on 2026-03-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_address_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
