# Generated by Django 5.2.11 on 2026-03-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_latitude_alter_user_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
    ]
