# Generated by Django 5.2.11 on 2026-03-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_address_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
