# Generated by Django 6.0.2 on 2026-03-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_partnerbankdetail_payoutrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payoutrequest",
            name="partner",
        ),
        migrations.DeleteModel(
            name="PartnerBankDetail",
        ),
        migrations.DeleteModel(
            name="PayoutRequest",
        ),
    ]
