# Generated by Django 6.0.2 on 2026-03-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
    ]
