# Generated by Django 5.2.11 on 2026-03-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_otp_code'),
        ('accounts', '0020_user_is_verified'),
    ]

    operations = [
    ]
