# Generated by Django 5.2.11 on 2026-02-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_servicetype_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
