# Generated by Django 5.2.11 on 2026-03-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_id_alter_orderitem_id'),
        ('orders', '0007_order_pickup_datetime'),
    ]

    operations = [
    ]
