# Generated by Django 5.2.11 on 2026-03-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_id', models.CharField(help_text='e.g., normal, 1_day, premium', max_length=50, unique=True)),
                ('title', models.CharField(help_text='e.g., Premium', max_length=50)),
                ('subtitle', models.CharField(help_text='e.g., 5-6 Hours', max_length=50)),
                ('charge_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g., 0.05 for 5%, 0.10 for 10%', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
