# Generated by Django 5.2.11 on 2026-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_order_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("pickup", "Picked Up"),
                    ("processing", "Processing"),
                    ("shipping", "Shipping"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
