# Generated by Django 5.2.11 on 2026-03-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_orderitem_accepted_at_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="accepted_at",
        ),
        migrations.AddField(
            model_name="order",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
