# Generated by Django 5.2.11 on 2026-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_remove_orderitem_accepted_at_order_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
