# Generated by Django 5.2.11 on 2026-03-08 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_order_is_paid_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, 
                max_digits=10,
                default=0.00
            ),
            preserve_default=False,
        ),
    ]
