# Generated by Django 5.2.11 on 2026-03-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_order_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_mode",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("ONLINE", "Online Payment")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
