# Generated by Django 6.0.2 on 2026-03-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_partnerwallet_payoutrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payoutrequest",
            name="partner",
        ),
        migrations.DeleteModel(
            name="PartnerWallet",
        ),
        migrations.DeleteModel(
            name="PayoutRequest",
        ),
    ]
