# Generated by Django 5.2.11 on 2026-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_remove_payoutrequest_partner_delete_partnerwallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_deadline_notified",
            field=models.BooleanField(default=False),
        ),
    ]
