# Generated by Django 5.2.11 on 2026-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_is_deadline_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
