# Generated by Django 6.0.2 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner_order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
