# Generated by Django 5.2.13 on 2026-04-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_partner_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
